/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */

@import Foundation;

@class AVTAvatarInstance;

@interface AVTPuppet: NSObject
@property (nonatomic) bool arMode;
@property (readonly) SCNNode *avatarNode;
@property (readonly) SCNNode *headNode;
@property (readonly) SCNNode *neckNode;
+ (id)puppetNamed:(id)arg1 options:(id)arg2;
+ (id)puppetNames;
+ (UIImage *)thumbnailForPuppetNamed:(id)arg1 options:(id)arg2;
@end
